Examen2/Models/Auto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Examen2.Models
{
	public partial class Auto
	{
		[Key]
		[Display(Name ="Id")]
		public int idAuto { get; set; }
		public string Modelo { get; set; }
		public string Placa { get; set; }
		public int Año { get; set; }

		[Display(Name ="Marca")]
		public int idMarca { get; set; }
	}
}

Examen2/Models/AutoParcial.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Examen2.Models
{
	public partial class Auto
	{
		[Display(Name ="Marca")]
		public string NombreMarca { get; set; }
	}
}

Examen2/Models/Marca.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Examen2.Models
{
	public class Marca
	{
		public int IdMarca { get; set; }
		public string Nombre { get; set; }
	}
}

Examen2/Models/Viaje.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Examen2.Models
{
	public class Viaje
	{
		public int ViajeId { get; set; }
		public string Origen { get; set; }
		public string Destino { get; set; }

		public DateTime FechaPartida { get; set; }
		public DateTime FechaLLegada { get; set; }
		public string NombreConductor { get; set; }
		public string ModeloAuto { get; set; }
	}
}

Examen2/Controllers/VehiculoController.cs
using Examen2.ADO;
using Examen2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Examen2.Controllers
{
    public class VehiculoController : Controller
    {
        // GET: Vehiculo
        public ActionResult Index()
        {
            return View();
        }

        // Declarar los ADOS
        AutoADO adoAuto = new AutoADO();
        MarcaADO adoMarca = new MarcaADO();
        public ActionResult ListarAutos()
        {
            List<Auto> lista = adoAuto.Listar();
            return View(lista);
        }

        public ActionResult RegistrarAuto()
        {
            ViewBag.marcas = adoMarca.Listar();
            return View(new Auto());
        }

        [HttpPost]
        public ActionResult RegistrarAuto(Auto a)
        {
            int resultado = adoAuto.Insertar(a);
            return RedirectToAction("ListarAutos");
        }

        public ActionResult EliminarAuto(int id)
        {
            int resultado = adoAuto.Eliminar(id);
            return RedirectToAction("ListarAutos");
        }

        public ActionResult VerAuto(int id)
        {
            Auto a = adoAuto.Obtener(id);
            return View(a);
        }
        public ActionResult EditarAuto(int id)
        {
            Auto a = adoAuto.Obtener(id);
            ViewBag.marcas = adoMarca.Listar();

            return View(a);
        }
        [HttpPost]
        public ActionResult EditarAuto(Auto a)
        {
            int resultado = adoAuto.Actualizar(a);
            return RedirectToAction("ListarAutos");
        }
    }
}

Examen2/Controllers/ViajesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Examen2.Models;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

namespace Examen2.Controllers
{
	public class ViajesController : Controller
	{

		SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["CNX"].ConnectionString);
		List<Viaje> BuscarViajesXAnio(string anio)
		{
			List<Viaje> resultado = new List<Viaje>();
			SqlCommand cmd = new SqlCommand("SP_VIAJES_X_ANIO", cn);
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.Parameters.AddWithValue("@anio", anio);
			cn.Open();
			SqlDataReader dr = cmd.ExecuteReader();
			while (dr.Read())
			{
				Viaje v = new Viaje();
				v.ViajeId = dr.GetInt32(0);
				v.Origen = dr.GetString(1);
				v.Destino = dr.GetString(2);
				v.FechaPartida = dr.GetDateTime(3);
				v.FechaLLegada = dr.GetDateTime(4);
				v.NombreConductor = dr.GetString(5);
				v.ModeloAuto = dr.GetString(6);
				resultado.Add(v);

			}
			dr.Close();
			cn.Close();
			return resultado;
		}

		List<Viaje> BuscarViajesXConductorYAnio(string conductor, string anio)
		{
			List<Viaje> resultado = new List<Viaje>();
			SqlCommand cmd = new SqlCommand("SP_VIAJES_X_CONDUCTOR_Y_ANIO_PARTIDA", cn);
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.Parameters.AddWithValue("@conductor", conductor);
			cmd.Parameters.AddWithValue("@anio", anio);
			cn.Open();
			SqlDataReader dr = cmd.ExecuteReader();
			while (dr.Read())
			{
				Viaje v = new Viaje();
				v.ViajeId = dr.GetInt32(0);
				v.Origen = dr.GetString(1);
				v.Destino = dr.GetString(2);
				v.FechaPartida = dr.GetDateTime(3);
				v.FechaLLegada = dr.GetDateTime(4);
				v.NombreConductor = dr.GetString(5);
				v.ModeloAuto = dr.GetString(6);
				resultado.Add(v);

			}
			dr.Close();
			cn.Close();
			return resultado;
		}

		List<Viaje> BuscarViajesXAutoYAnio(string auto, string anio)
		{
			List<Viaje> resultado = new List<Viaje>();
			SqlCommand cmd = new SqlCommand("SP_VIAJES_X_AUTO_Y_ANIO_PARTIDA", cn);
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.Parameters.AddWithValue("@auto", auto);
			cmd.Parameters.AddWithValue("@anio", anio);
			cn.Open();
			SqlDataReader dr = cmd.ExecuteReader();
			while (dr.Read())
			{
				Viaje v = new Viaje();
				v.ViajeId = dr.GetInt32(0);
				v.Origen = dr.GetString(1);
				v.Destino = dr.GetString(2);
				v.FechaPartida = dr.GetDateTime(3);
				v.FechaLLegada = dr.GetDateTime(4);
				v.NombreConductor = dr.GetString(5);
				v.ModeloAuto = dr.GetString(6);
				resultado.Add(v);

			}
			dr.Close();
			cn.Close();
			return resultado;
		}

		public ActionResult Index()
		{
			return View();
		}

		public ActionResult BuscarViajesPorAnio(string anio = null)
		{
			List<Viaje> lista = new List<Viaje>();
			if(!string.IsNullOrEmpty(anio))
				lista = BuscarViajesXAnio(anio);
			return View(lista);
		}

		public ActionResult BuscarViajesPorConductorYAnio(string conductor = null, string anio = null)
		{
			List<Viaje> lista = new List<Viaje>();
			if (!string.IsNullOrEmpty(conductor) && !string.IsNullOrEmpty(anio))
				lista = BuscarViajesXConductorYAnio(conductor, anio);
			return View(lista);
		}

		public ActionResult BuscarViajesPorAutoYAnio(string auto = null, string anio = null)
		{
			List<Viaje> lista = new List<Viaje>();
			if (!string.IsNullOrEmpty(auto) && !string.IsNullOrEmpty(anio))
				lista = BuscarViajesXAutoYAnio(auto, anio);
			return View(lista);
		}

	}
}

Examen2/Views/General/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>POOII - Examen 2</title>
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	@Styles.Render("~/Content/css")
</head>
<body>
	<div class="page">
		<span class="menu_toggle text-white">
			<i class="menu_open fa fa-bars fa-lg"></i>
			<i class="menu_close fa fa-times fa-lg"></i>
		</span>
		<ul class="menu_items">
			<li>
				<a href="@Url.Action("Index", "Vehiculo")">
					<i class="icon fa fa-home"></i>
					Inicio
				</a>
			</li>
			<li>
				<a href="@Url.Action("ListarAutos", "Vehiculo")">
					<i class="icon fa fa-car"></i>
					AUTOS
				</a>
			</li>

			<li>
				<a href="@Url.Action("BuscarViajesPorAnio", "Viajes")" id="dropdown" class="dropdown">
					<i class="icon fa fa-list"></i>
					CONSULTAR
				</a>
			</li>
		</ul>
		<main class="content">
			<div class="content_inner">
				@RenderBody()
			</div>

		</main>

		<footer class="footer bg-dark p-3 text-center">
			<p class="h5 mb-0">Made by &copy;<a href="https://juliorivera.dev" target="_blank" rel="noopener noreferrer" class="text-white">Julio Cesar Rivera</a></p>
		</footer>
	</div>
	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

	@Scripts.Render("~/bundles/app")
	@RenderSection("scripts", required: false)


</body>
</html>

Examen2/Views/Vehiculo/EditarAuto.cshtml
@model Examen2.Models.Auto

@{
	ViewBag.Title = "EditarAuto";
	Layout = "~/Views/General/_Layout.cshtml";
}
	<div class="container d-flex flex-column justify-content-center h-100 ">
		<h2>EditarAuto</h2>

		@using (Html.BeginForm())
		{
			@Html.AntiForgeryToken()

			@Html.ValidationSummary(true, "", new { @class = "text-danger" })

			@Html.HiddenFor(model => model.idAuto)

			<div class="form-group">
				@Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "control-label col-md-2 pl-0" })

				@Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })

			</div>
			<div class="form-group">
				@Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2 pl-0" })

				@Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })

			</div>



			<div class="form-group">
				@Html.LabelFor(model => model.Año, htmlAttributes: new { @class = "control-label col-md-2 pl-0" })

				@Html.EditorFor(model => model.Año, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.Año, "", new { @class = "text-danger" })

			</div>


			<div class="form-group">
				@Html.LabelFor(model => model.idMarca, htmlAttributes: new { @class = "control-label col-md-2 pl-0" })

				@Html.DropDownListFor(model => model.idMarca, new SelectList(ViewBag.marcas, "idMarca", "Nombre"), htmlAttributes: new { @class = "custom-select" })
				@Html.ValidationMessageFor(model => model.idMarca, "", new { @class = "text-danger" })

			</div>

			<div class="form-group">
				<div class="col-md-offset-2">
					<input type="submit" value="Actualizar" class="btn btn-primary" />
					@Html.ActionLink("Volver al Listado", "ListarAutos", null, new { @class = "btn btn-outline-primary" })
				</div>
			</div>
		}
	</div>

Examen2/Views/Vehiculo/Index.cshtml
@{
	ViewBag.Title = "Index";
	Layout = "~/Views/General/_Layout.cshtml";
}

<h2 class=" titulo1"><b>CONSORCIO</b></h2>

<h2 class=" titulo2"><b>LEYVA</b></h2>


<!-- 3D Slideshow Section -->
<div class="slideshow">
	<div class="skills-container">
		<div class="skills-carousel">
			<figure class="skills-slide">
				<img src="~/Img/1.jpg" alt="" class="skills-logo html-logo">
			</figure>
			<figure class="skills-slide">
				<img src="~/Img/2.jpg" alt="" class="skills-logo css-logo">
			</figure>
			<figure class="skills-slide">
				<img src="~/Img/3.jpg" alt="" class="skills-logo js-logo">
			</figure>
			<figure class="skills-slide">
				<img src="~/Img/4.jpg" alt="" class="skills-logo jquery-logo">
			</figure>
			<figure class="skills-slide">
				<img src="~/Img/5.jpg" alt="" class="skills-logo bootstrap-logo">
			</figure>
			<figure class="skills-slide">
				<img src="~/Img/6.jpg" alt="" class="skills-logo wordpress-logo">
			</figure>
			<figure class="skills-slide">
				<img src="~/Img/7.jpg" alt="" class="skills-logo git-logo">
			</figure>
			<figure class="skills-slide">
				<img src="~/Img/8.jpg" alt="" class="skills-logo github-logo">
			</figure>
			<figure class="skills-slide">
				<img src="~/Img/2.jpg" alt="" class="skills-logo ally-logo">
			</figure>
			<figure class="skills-slide">
				<img src="~/Img/4.jpg" alt="" class="skills-logo ps-logo">
			</figure>
			<figure class="skills-slide">
				<img src="~/Img/6.jpg" alt="" class="skills-logo ai-logo">
			</figure>
		</div>
	</div>
</div>

Examen2/Views/Vehiculo/ListarAutos.cshtml
@model IEnumerable<Examen2.Models.Auto>

@{
	ViewBag.Title = "ListarAutos";
	Layout = "~/Views/General/_Layout.cshtml";
}

<h2 class="text-center">AUTOS</h2>

@Html.ActionLink("Nuevo Auto", "RegistrarAuto",null, new { @class = "btn btn-primary mb-3"})

<table class="table table-dark">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.idAuto)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.NombreMarca)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Modelo)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Placa)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Año)
		</th>
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.idAuto)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.NombreMarca)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Modelo)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Placa)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.Año)
			</td>
			<td>
				@Html.ActionLink("Editar", "EditarAuto", new { id = item.idAuto }) |
				@Html.ActionLink("Detalles", "VerAuto", new { id = item.idAuto }) |
				@Html.ActionLink("Eliminar", "EliminarAuto", new { id = item.idAuto })
			</td>
		</tr>
	}

</table>

Examen2/Views/Vehiculo/RegistrarAuto.cshtml
@model Examen2.Models.Auto

@{
	ViewBag.Title = "Registrar Auto";
	Layout = "~/Views/General/_Layout.cshtml";
}

<div class="container d-flex flex-column justify-content-center h-100 ">
	<h2 class="text-center">NUEVO AUTO</h2>

	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		@Html.ValidationSummary(true, "", new { @class = "text-danger" })

		<div class="form-group">
			@Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "control-label col-md-2 pl-0" })

			@Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "form-control col" } })
			@Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })

		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Año, htmlAttributes: new { @class = "control-label col-md-2 pl-0" })

			@Html.EditorFor(model => model.Año, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Año, "", new { @class = "text-danger" })

		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2 pl-0" })

			@Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })

		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.idMarca, htmlAttributes: new { @class = "control-label col-md-2 pl-0" })

			@Html.DropDownListFor(model => model.idMarca, new SelectList(ViewBag.marcas, "idMarca", "Nombre"), htmlAttributes: new { @class = "custom-select" })
			@Html.ValidationMessageFor(model => model.idMarca, "", new { @class = "text-danger" })

		</div>

		<div class="form-group">
			<div class="col-md-offset-2">
				<input type="submit" value="Registrar" class="btn btn-primary" />
				@Html.ActionLink("Volver al Listado", "ListarAutos", null, new { @class = "btn btn-outline-primary" })

			</div>
		</div>
	}
</div>

Examen2/Views/Vehiculo/VerAuto.cshtml
@model Examen2.Models.Auto

@{
    ViewBag.Title = "Ver Auto";
    Layout = "~/Views/General/_Layout.cshtml";
}
	<div class="container d-flex flex-column justify-content-center h-100 ">
		<h2 class="text-center m-3">DETALLE AUTO</h2>

		<div>
			<dl class="dl-horizontal text-center card pb-0 pt-3 pb-3">
				<dt>
					@Html.DisplayNameFor(model => model.NombreMarca)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.NombreMarca)
				</dd>
				<dt>
					@Html.DisplayNameFor(model => model.Modelo)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.Modelo)
				</dd>
				<dt>
					@Html.DisplayNameFor(model => model.Placa)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.Placa)
				</dd>
				<dt>
					@Html.DisplayNameFor(model => model.Año)
				</dt>

				<dd>
					@Html.DisplayFor(model => model.Año)
				</dd>


			</dl>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 d-flex justify-content-center">
				@Html.ActionLink("Editar", "EditarAuto", new { id = Model.idAuto },new { @class= "btn btn-primary mr-3" } )
				@Html.ActionLink("Volver al Listado", "ListarAutos", null, new { @class = "btn btn-outline-primary" })

			</div>
		</div>
	</div>

Examen2/Views/Viajes/BuscarViajesPorAnio.cshtml
@model IEnumerable<Examen2.Models.Viaje>

@{
	ViewBag.Title = "Buscar Viajes por Año";
}

<div class="row ">
	<div class="col d-flex justify-content-center">
		<a href="@Url.Action("BuscarViajesPorAnio")" class="btn btn-primary mr-3">Buscar Viaje Por Año</a>
		<a href="@Url.Action("BuscarViajesPorConductorYAnio")" class="btn btn-outline-primary mr-3 ">Buscar Viaje Por Conductor Y Año</a>
		<a href="@Url.Action("BuscarViajesPorAutoYAnio")" class="btn btn-outline-primary mr-3">Buscar Viaje Por Auto y Año</a>
	</div>
</div>

<h2 class="text-center m-5 font-weight-bold">BUSCAR VIAJES POR AÑO DE PARTIDA</h2>

@using (Html.BeginForm())
{
	<div class="row mb-5 w-50 mr-auto ml-auto">
		<div class="col">
			@{
				var listado = new List<SelectListItem>()
				{
					new SelectListItem()
					{
						Text = "Seleccione el Año de Partida",
						Value = null,
					},
					new SelectListItem()
					{
						Text = "2011",
						Value = "2011",
					},
					new SelectListItem()
					{
						Text = "2012",
						Value = "2012",
					},
				};
			}
			@Html.DropDownList("anio", listado, new { @class = "custom-select" })

		</div>
		<div class="col-1">
			<div class="input-group-append">
				<button class="btn btn-primary" id="button-addon2">Buscar</button>
			</div>
		</div>


	</div>

}

@Html.Partial("_PartialViajes")

Examen2/Views/Viajes/BuscarViajesPorAutoYAnio.cshtml
@model IEnumerable<Examen2.Models.Viaje>

@{
	ViewBag.Title = "Buscar Viajes Por Auto y Anio";
}

	<div class="row ">
		<div class="col d-flex justify-content-center">
			<a href="@Url.Action("BuscarViajesPorAnio")" class="btn btn-outline-primary mr-3">Buscar Viaje Por Año</a>
			<a href="@Url.Action("BuscarViajesPorConductorYAnio")" class="btn btn-outline-primary mr-3 ">Buscar Viaje Por Conductor Y Año</a>
			<a href="@Url.Action("BuscarViajesPorAutoYAnio")" class="btn btn-primary mr-3">Buscar Viaje Por Auto y Año</a>
		</div>
	</div>

<h2 class="title text-center m-5 font-weight-bold">BUSCAR VIAJES POR AUTO Y AÑO DE PARTIDA</h2>



@using (Html.BeginForm())
{
<div class="row m-5">
	<div class="col">
		<div class="input-group">
			@Html.TextBox("auto", null, new { @class = "form-control", placeholder = "Modelo de Auto" })
		</div>
	</div>


	<div class="col">
		@{
			var listado = new List<SelectListItem>()
			{
					new SelectListItem()
					{
						Text = "Seleccione el Año de Partida",
						Value = null,
					},
					new SelectListItem()
					{
						Text = "2011",
						Value = "2011",
					},
					new SelectListItem()
					{
						Text = "2012",
						Value = "2012",
					},
				};
		}
		@Html.DropDownList("anio", listado, new { @class = "custom-select" })

	</div>
	<div class="col-2">
		<div class="input-group-append">
			<button class="btn btn-primary btn-block" id="button-addon2">Buscar</button>
		</div>
	</div>
</div>

}


@Html.Partial("_PartialViajes")

Examen2/Views/Viajes/BuscarViajesPorConductorYAnio.cshtml
@model IEnumerable<Examen2.Models.Viaje>

@{
	ViewBag.Title = "BUSCAR VIAJES POR CONDUCTOR Y AÑO";
}

<div class="row ">
	<div class="col d-flex justify-content-center">
		<a href="@Url.Action("BuscarViajesPorAnio")" class="btn btn-outline-primary mr-3">Buscar Viaje Por Año</a>
		<a href="@Url.Action("BuscarViajesPorConductorYAnio")" class="btn btn-primary mr-3 ">Buscar Viaje Por Conductor Y Año</a>
		<a href="@Url.Action("BuscarViajesPorAutoYAnio")" class="btn btn-outline-primary mr-3">Buscar Viaje Por Auto y Año</a>
	</div>
</div>
<h2 class="title text-center m-5 font-weight-bold">BUSCAR VIAJES POR CONDUCTOR Y AÑO DE PARTIDA</h2>

@using (Html.BeginForm())
{
	<div class="row m-5">
		<div class="col">
			<div class="input-group">
				@Html.TextBox("conductor", null, new { @class = "form-control", placeholder = "Nombre del Conductor" })
			</div>
		</div>


		<div class="col">
			@{
				var listado = new List<SelectListItem>()
				{
					new SelectListItem()
					{
						Text = "Seleccione el Año de Partida",
						Value = null,
					},
					new SelectListItem()
					{
						Text = "2011",
						Value = "2011",
					},
					new SelectListItem()
					{
						Text = "2012",
						Value = "2012",
					},
				};
			}
			@Html.DropDownList("anio", listado, new { @class = "custom-select" })

		</div>
		<div class="col-2">
			<div class="input-group-append">
				<button class="btn btn-primary btn-block" id="button-addon2">Buscar</button>
			</div>
		</div>
	</div>

}


@Html.Partial("_PartialViajes")

Examen2/Views/Viajes/_PartialViajes.cshtml
@model IEnumerable<Examen2.Models.Viaje>

	<table class="table table-dark">
		<thead>
			<tr>
				<th>ID</th>
				<th>Origen</th>
				<th>Destino</th>
				<th>Fecha de Partida</th>
				<th>Fecha de LLegada</th>
				<th>Conductor</th>
				<th>Modelo de Auto</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var v in Model)
			{
				<tr>
					<td>@Html.DisplayFor(modelitem => v.ViajeId)</td>
					<td>@Html.DisplayFor(modelitem => v.Origen)</td>
					<td>@Html.DisplayFor(modelitem => v.Destino)</td>
					<td>@Html.DisplayFor(modelitem => v.FechaPartida)</td>
					<td>@Html.DisplayFor(modelitem => v.FechaLLegada)</td>
					<td>@Html.DisplayFor(modelitem => v.NombreConductor)</td>
					<td>@Html.DisplayFor(modelitem => v.ModeloAuto)</td>
				</tr>
			}
		</tbody>
	</table>